### ISSUE TITLE
[DOCS] ES community clients update

### ISSUE THREAD

**Issue by barbulescu** [jillesvangurp/kt-search#102]
**Describe the issue**

[ES Community Kotlin clients](https://www.elastic.co/guide/en/elasticsearch/client/community/current/index.html#kotlin) could be updated with the link to kt-search instead of having the link to old client.

**Will you be able to help with a pull request?**

Yes

**Comment by jillesvangurp** [comment]
https://github.com/elastic/elasticsearch/compare/main...jillesvangurp:elasticsearch:patch-2

Thanks for pointing that out. I actually added the old es-kotlin-wrapper there ages ago. This should fix it.
