### ISSUE TITLE
[FEAT] Add score_mode and ignore_unmapped parameters to NestedQuery

### ISSUE THREAD

**Issue by tomasborrella** [jillesvangurp/kt-search#107]
**Describe the enhancement**

On a nested query there are two optional parameters (`score_mode` and `ignore_unmapped`) that modify the query result. Those two parameters are not defined in NestedQuery class (that only has the required parameters `path` and `query`).

reference: [elastic Nested query documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-nested-query.html)

**Comment by jillesvangurp** [comment]
Thanks for reporting. I'll add those. 

As a workaround, you can use schema less manipulation of the JsonDsl to add properties like this since it is just a `Map<String,Any>`:

```
this["score_mode"] = "..."
this["ignore_unmpapped"] = true
```

**Comment by barbulescu** [comment]
I changed `gt=2` to `gt=4` in NestedQueryTest.shouldCreatedMappingWithNestedFieldAndQuery test and I would expect total to be 0 but it is still 2. 

Did I break something when I changed `SearchDSL.nested` to `QueryClauses.nested`?

I see in the log that body is `{}`
