### ISSUE TITLE
[FEAT] Support for join type mapping 

### ISSUE THREAD

**Issue by csh97** [jillesvangurp/kt-search#113]
**Describe the enhancement**

Support for adding join type to an index mapping
See Elasticsearch documentation: https://www.elastic.co/guide/en/elasticsearch/reference/current/parent-join.html

**Why is this needed?**

Allows for parent/child relations in an index

**Will you be able to help with a pull request?**

I have created a pull request already for this feature: https://github.com/jillesvangurp/kt-search/pull/112

**Comment by jillesvangurp** [comment]
closed by #112
