### ISSUE TITLE
[FEAT] Support for join queries

### ISSUE THREAD

**Issue by csh97** [jillesvangurp/kt-search#116]
**Describe the enhancement**

Elasticsearch has 4 different join queries: https://www.elastic.co/guide/en/elasticsearch/reference/current/joining-queries.html
Nested queries are already supported, however support for has_parent, has_child and parent_id is missing

**Why is this needed?**

To be able to query when using join fields

**Will you be able to help with a pull request?**

I have created a pull request for this feature: https://github.com/jillesvangurp/kt-search/pull/115

**Comment by jillesvangurp** [comment]
closed by #115
