### ISSUE TITLE
[DOCS] Maven dependency

### ISSUE THREAD

**Issue by dybarsky** [jillesvangurp/kt-search#127]
**Describe the issue**

Gradle allows to include all artefacts from group, but maven doesn't. That means, it's needed to specify all jvm targeting artefacts explicitly as dependencies. This part is missing in documentation and people who don't know much about kotlin multiplatform internals find it hard to add dependency into project

**Will you be able to help with a pull request?**

I updated readme file already, but I can't push a new branch to make a pull request.

**Comment by jillesvangurp** [comment]
The README is generated, you'll have to update the code that generates it in docs. To create a pull request, please fork the repository and create a branch on your own repository and create a pull request from there.

**Comment by dybarsky** [comment]
@jillesvangurp Gotcha. Thank you. I will check.

**Comment by dybarsky** [comment]
@jillesvangurp Added a PR #128. Feel free to change what you think fits better into your code conduct.
