### ISSUE TITLE
[FEAT] term boolean support

### ISSUE THREAD

**Issue by cdekok** [jillesvangurp/kt-search#129]
**Describe the enhancement**

Add support to the term to accept a boolean

```kotlin
term(query.field, true)
```

**Why is this needed?**

Currently it only accepts strings which is a bit awkward to use when dealing with boolean values

**How do you think it should be done?**

Adding an additional dsl like.

```kotlin
fun QueryClauses.term(
    field: String,
    value: Boolean,
    block: (TermQueryConfig.() -> Unit)? = null
)
```

**Will you be able to help with a pull request?**

Yes

**Comment by jillesvangurp** [comment]
Sounds good, feel free to add this with a small PR.
