### ISSUE TITLE
[FEAT] script based sorting support 

### ISSUE THREAD

**Issue by yonghee12** [jillesvangurp/kt-search#130]
**Describe the enhancement**

Add support to the script based sorting feature

```kotlin
SearchDSL().apply {
    sort {
        addScript(
            order = SortOrder.ASC,
            type = "number",
            source = "doc['field_name'].value * params.factor;",
            lang = "painless",
            params = mapOf("factor" to 1.1),
        )
    }
}
```

**Why is this needed?**

<img width="450" alt="Screen Shot 2024-04-11 at 6 21 50 PM" src="https://github.com/jillesvangurp/kt-search/assets/24601847/b6347edb-6e30-493a-aca2-b9b42ae0506b">

Sometimes business requirements require complex sorting logic. elastic search query can solve this with script-based sorting(e.g. https://www.elastic.co/guide/en/elasticsearch/reference/current/sort-search-results.html#script-based-sorting), and it would be nice to support this in kt-search as well.
Also, you can query basic field name based sorting and script based sorting in one sort array to handle complex requirements.

**How do you think it should be done?**

If you add the methods below inside the [SortBuilder](https://github.com/jillesvangurp/kt-search/blob/9c0999807d490db77ee52f755f2b786c48b726d5/search-dsls/src/commonMain/kotlin/com/jillesvangurp/searchdsls/querydsl/search-dsl.kt#L122
), you should be able to use them in conjunction with your existing sorting methods.

```kotlin
fun addScript(
    order: SortOrder = SortOrder.DESC,
    type: String,
    source: String,
    params: Map<String, Any>? = emptyMap(),
    lang: String? = null,
) {
    _sortFields.add(
        withJsonDsl {
            this["_script"] = withJsonDsl {
                this["order"] = order.name
                this["type"] = type
                this["script"] = scriptBuilder(source, params, lang)
            }
        },
    )
}

private fun scriptBuilder(
    source: String,
    params: Map<String, Any>? = emptyMap(),
    lang: String? = "painless",
): JsonDsl {
    return withJsonDsl {
        this["source"] = source
        this["lang"] = lang
        if (params?.isNotEmpty() == true) {
            this["params"] = withJsonDsl {
                params.forEach { (key, value) -> this[key] = value }
            }
        }
    }
}
```

**Will you be able to help with a pull request?**

Yes

**Comment by jillesvangurp** [comment]
Please go ahead with the PR if you have time.

**Comment by yonghee12** [comment]
closed by https://github.com/jillesvangurp/kt-search/pull/131
