### ISSUE TITLE
Unknown repository

### ISSUE THREAD

**Issue by alexanderpichler-cpi** [jillesvangurp/kt-search#148]
**Describe the issue**

Hi, I tried to use the lib ,but you are sure that the repository is right?

https://maven.tryformation.com/releases doesn't exist

I tried also your demo project https://github.com/formation-res/kt-fullstack-demo and get this gradle errors

:server:main: Could not resolve com.jillesvangurp:search-client:2.1.25.
:server:main: Could not resolve com.jillesvangurp:search-dsls:2.1.25.

**Comment by jillesvangurp** [comment]
The directory is not browsable via gcp but it does exist if you hit it with specific paths like gradle would do. For example: https://maven.tryformation.com/releases/com/jillesvangurp/search-client/2.2.1/search-client-2.2.1-sources.jar works fine.

2.2.1 is the latest release.

Did you configure the repository correctly?

**Comment by igormicaelribeiro** [comment]
Hi, I tried either ways, but both doesn't work.

Can you provide any alternative to use this lib using gradle ?

**Comment by jillesvangurp** [comment]
Sorry, you clearly have some dependency conflict on your side. I can't fix that.
