### ISSUE TITLE
[DOCS] Would be nice to have something about searching for non-string values.

### ISSUE THREAD

**Issue by sleekweasel** [jillesvangurp/kt-search#22]
**Describe the issue**

I'm trying to query on an integer field. I have the below working, but it took some digging to work out - could you drop something like this into the docs? (or something better!)

            query =
                bool {
                    filter(
                        listOf(
                            disMax {
                                queries(
                                    listOf(
                                       ESQuery("match_phrase", JsonDsl().apply {
                                            put("tc_build_id", 18941877)
                                        }),
                                        ESQuery("match_phrase", JsonDsl().apply {
                                            put("tc_build_id", 18992070)
                                        })
                                    )
                                )
                            }
                            , matchPhrase("type", "scenario")
                        )
                    )
                }

And I know I could lose the 'listOf' calls, but I'm leaving them in because I need to build the lists programmatically in my final code. :)

**Will you be able to help with a pull request?**

Sure - let me know if the above is acceptable as an example, and where you want it.

**Comment by jillesvangurp** [comment]
not sure what you want here. You want to do text matching on numeric fields?
