### ISSUE TITLE
[FEAT] Filter aggregations

### ISSUE THREAD

**Issue by jelle-blaauw** [jillesvangurp/kt-search#67]
**Describe the enhancement**

I'd like to be able to do filter aggregations, like so:
```
"aggs": {
  "my-agg-name": {
    "filter": {
      "bool": {
        "must": [{
          "nested": {
            "path": "someField",
            "query": {
              "bool": {
                "must": [{
                  "exists": { "field": "someField" }
                }, {
                  "term": {"someField.somePath": "someValue"}
                }]
              }
            }
          }
        }]
      }
    }
  },
  ...
}
```

**Why is this needed?**

It's an ElasticSearch feature, so it should be in this lib as well.

**How do you think it should be done?**

I think an extension to `AggQuery` can be made which uses a `BoolQuery` as the "body".

**Will you be able to help with a pull request?**

Maybe.

**Comment by jillesvangurp** [comment]
Cool thanks! That looks like it should work. When I find some time, I'll squeeze in a pull request. Might be a while because I'm super busy right now.
