### ISSUE TITLE
[FEAT] Configure a client without a port

### ISSUE THREAD

**Issue by legzo** [jillesvangurp/kt-search#70]
**Describe the enhancement**

I would like to be able to specify a connection URL without a port.

**Why is this needed?**

My ES cluster has a proxy in front of it and the API responds when no port is specified but does not responds if I specify 80 as port. So, right now, I can't use `kt-search` at all (unless I missed something in the docs, but I checked the code and it seems that `port` is non nullable in `Node` so....)

**Will you be able to help with a pull request?**

I sure can. Maybe it is possible to just make `port` nullable in `Node` data class, but it may have implications that I don't suspect... :)

Cheers

**Comment by jillesvangurp** [comment]
Good suggestion. Doing a quick fix for this.
