### ISSUE TITLE
[FEAT] Deploy to Maven Central

### ISSUE THREAD

**Issue by hanswesterbeek** [jillesvangurp/kt-search#82]
**Describe the enhancement**

Deploys artifacts, sources etc to Maven Central.

**Why is this needed?**

There are lots of organizations that will not allow their devs to use libs that do not at least appear with the appropriate GPG signatures. This hampers adoption and growth of community for `kt-search`.

**How do you think it should be done?**

[Technically, this is how]
](https://h4pehl.medium.com/publish-your-gradle-artifacts-to-maven-central-f74a0af085b1) Some additional credentials also need to be stup.

**Will you be able to help with a pull request?**

Yes, happy to help out and integrate it into github actions,  but would have to be given permissions for it.

**Comment by jillesvangurp** [comment]
WONT FIX unfortunately. I've sunk way too much time in this already and failed miserably. Something about multi module and multi platform builds that just won't work as advertised with maven central and remains completely undocumented. I've tried; multiple times and have nothing to show for my efforts.

**Comment by hanswesterbeek** [comment]
Ok, well i'm willing to give it a try if you let me :)
