### ISSUE TITLE
[DOCS] examples on how to use KTorRestClient to connect to amazon serverless opensearch

### ISSUE THREAD

**Issue by vtkstef** [jillesvangurp/kt-search#84]
**Connect to Amazon Serverless opensearch instance**

I would like to know how to configure a KTorRestClient instance to communicate with an instance of aws serverless opensearch, as the java client [documentation](https://opensearch.org/docs/latest/clients/java/#connecting-to-amazon-opensearch-serverless) does

**Comment by jillesvangurp** [comment]
Sorry, I only saw this just now. I have no access to an AWS hosted opensearch cluster. 

I found this gist that outlines how to connect to AWS Opensearch clusters using curl:

https://gist.github.com/hassaku63/e3ed3cac288d429563cdddf1768613d6

You might be able to adapt that. If you get this working, I would appreciate a pull request to document this.

**Comment by jillesvangurp** [comment]
I updated the documentation with some notes. Again, pull requests welcome for this but I have no AWS account to test this with. The core issue is their api signing needs to be implemented somewhere.
