### ISSUE TITLE
[BUG] indexDocument version should be a Long

### ISSUE THREAD

**Issue by frisi** [jillesvangurp/kt-search#86]
The `version` param in `SearchClient.indexDocument` should be of type `Long` instead of `Int` to support all usecases (eg using millis-since-epoch as version)

see also [Elasticsearch Docs on indexing](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/docs-index_.html#index-versioning):

> The value provided must be a numeric, long value greater than or equal to 0, and less than around 9.2e+18.

As a workaround, one can use extraParameters

```
   val version = 1697624118596L
   client.indexDocument(
                indexName,
                doc
                id = id,
//                version = version.toInt(),
                versionType = VersionType.External,
                extraParameters = mapOf(
                    "version" to "$version"
                ),
```

**Your context**

- search-client 2.1.1"

**Will you be able to help with a pull request?**

no, sorry ;-)

**Comment by jillesvangurp** [comment]
Thanks for reporting this. You are right, this should be a Long.
