### ISSUE TITLE
[FEAT] enable setting refresh_interval in createIndex

### ISSUE THREAD

**Issue by Tyngstast** [jillesvangurp/kt-search#95]
**Describe the enhancement**

I want to enable setting refresh_interval in IndexSettings for createIndex. 

More info: https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html#index-refresh-interval-setting

**Why is this needed?**

It's relevant for performance optimizations.

**Will you be able to help with a pull request?**

Optional, but do let me know if you plan to do work.

**Comment by jillesvangurp** [comment]
I don't have all the parameters supported indeed but it's easy to go schema-less here and just 
manually update the underlying map:

```
client.createIndex("an-index") {
   settings {
      replicas=1
      shards=3
      this["refresh_interval"]=5
   }
}
```

If you have time to do a pull request, it's pretty easy to add this to the DSL. Not planning to do a lot of work on this soon but might eventually get around to this.

**Comment by barbulescu** [comment]
This can be closed as it was implemented in https://github.com/jillesvangurp/kt-search/pull/99 and https://github.com/jillesvangurp/kt-search/pull/100

**Comment by jillesvangurp** [comment]
Thanks again!

**Comment by jillesvangurp** [comment]
I created a release with your changes btw.
