### ISSUE TITLE
[FEAT] Reindex support

### ISSUE THREAD

**Issue by barbulescu** [jillesvangurp/kt-search#98]
Add support for Reindex operation: https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html

What would you like changed?

**Why is this needed?**

This is handy on copying data between indices and also on implementing something similar with Liquibase.

**How do you think it should be done?**

Not yet.

**Will you be able to help with a pull request?**

I will do this.

**Comment by jillesvangurp** [comment]
Cool! Be sure to either exclude opensearch with the right annotations or create an opensearch alternative if they have it. I think this was an x-pack feature back in the day.

**Comment by jillesvangurp** [comment]
closed by #99
